// Automatically generated by MockGen. DO NOT EDIT!
// Source: ../hydra_client.go

package mock_client

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of HydraClient interface
type MockHydraClient struct {
	ctrl     *gomock.Controller
	recorder *_MockHydraClientRecorder
}

// Recorder for MockHydraClient (not exported)
type _MockHydraClientRecorder struct {
	mock *MockHydraClient
}

func NewMockHydraClient(ctrl *gomock.Controller) *MockHydraClient {
	mock := &MockHydraClient{ctrl: ctrl}
	mock.recorder = &_MockHydraClientRecorder{mock}
	return mock
}

func (_m *MockHydraClient) EXPECT() *_MockHydraClientRecorder {
	return _m.recorder
}

func (_m *MockHydraClient) Get() {
	_m.ctrl.Call(_m, "Get")
}

func (_mr *_MockHydraClientRecorder) Get() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Get")
}

func (_m *MockHydraClient) ReloadHydraServers() {
	_m.ctrl.Call(_m, "ReloadHydraServers")
}

func (_mr *_MockHydraClientRecorder) ReloadHydraServers() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReloadHydraServers")
}
